FROM php:8.2-fpm

# Install dependencies sistem
RUN apt-get update && apt-get install -y \
    libpng-dev libonig-dev libxml2-dev zip unzip git curl

# Install ekstensi PHP untuk Laravel & Database (MySQL/PostgreSQL)
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Ambil Composer terbaru
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .

# Install dependencies tanpa dev tools
RUN composer install --no-dev --optimize-autoloader

# Jalankan server langsung di port 80
EXPOSE 80
CMD php artisan serve --host=0.0.0.0 --port=80
